---
name: Build base container
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - Containerfile.base

permissions:
  contents: read

jobs:
  base:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}-base
      containerfile: ./Containerfile.base
