---
name: Build release
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --release --all-features
    - uses: actions/upload-artifact@v4
      with:
        name: release-bins
        path: |
          target/release/serve
          target/release/templater
        retention-days: 1

  serve:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}
      containerfile: ./Containerfile.serve
      artifact: release-bins

  cli:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}-cli
      containerfile: ./Containerfile.cli
      artifact: release-bins
