---
name: Build release
on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:

  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - run: cargo build --release --all-features
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: release-bins
        path: |
          target/release/serve
          target/release/templater
        retention-days: 1

  serve:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}
      containerfile: ./Containerfile.serve
      artifact: release-bins

  cli:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}-cli
      containerfile: ./Containerfile.cli
      artifact: release-bins
