---
name: Build base container
on:
  workflow_dispatch:
  schedule:
  - cron: '0 4 * * 1'
  push:
    branches:
    - main
    paths:
    - Containerfile.base
    - .github/workflows/build-basecontainer.yml

permissions:
  contents: read

jobs:
  base:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}-base
      containerfile: ./Containerfile.base
