---
name: Build base container
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - Containerfile.base

jobs:
  base:
    uses: ./.github/workflows/_container.yml
    with:
      image: ${{ github.repository }}-base
      containerfile: ./Containerfile.base
